version: '3.9'
services:
  db:
    image: postgres:latest
    container_name: weather_db
    environment:
      - POSTGRES_DB=wb_db
      - POSTGRES_USER=wb_user
      - POSTGRES_PASSWORD=wb_pass
    ports:
      - "5432:5432"
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
      - ./internal/pg/data:/var/lib/postgresql/data

  app:
    build: .
    container_name: weather-app
    ports:
      - "8181:8181"
    environment:
      POSTGRES_DB: "wb_db"
      POSTGRES_USER: "wb_user"
      POSTGRES_PASSWORD: "wb_pass"
    command: ./wait-for-postgres.sh db ./api
    restart: always
    depends_on:
      - db

volumes:
  data: